#!/bin/bash
# Production build script for era_native
# Builds the app with production backend URL and Basic Auth

set -e

# Get the directory where this script is located (era_scripts/)
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the project root directory (one level up)
PROJECT_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== ERA Production Build ===${NC}\n"

# Production configuration
PROD_BACKEND_URL="https://epoha.igroteh.su/backend/"
PROD_BASIC_AUTH_USERNAME="Anton"
PROD_BASIC_AUTH_PASSWORD="aoFa4-cah"

echo -e "${GREEN}Production Configuration:${NC}"
echo -e "  Backend URL: ${PROD_BACKEND_URL}"
echo -e "  Basic Auth:  ${PROD_BASIC_AUTH_USERNAME}:***"
echo ""

# Ask which project to build
echo -e "${YELLOW}Какой проект собирать?${NC}"
echo "  1) era_native  (мастерское приложение)"
echo "  2) era_players (приложение для игроков-купцов)"
echo ""
read -p "Выбор [1-2]: " PROJECT_CHOICE

case "$PROJECT_CHOICE" in
    2)
        PROJECT_APP="era_players"
        PROJECT_LABEL="era_players (игроки)"
        ;;
    *)
        PROJECT_APP="era_native"
        PROJECT_LABEL="era_native (мастера)"
        ;;
esac

echo ""
echo -e "${GREEN}Выбран проект: ${PROJECT_LABEL}${NC}\n"

# Ask user what game variant to build
echo -e "${YELLOW}Для какой версии игры собрать приложение?${NC}"
echo "  1) Era of Change (base-game)"
echo "  2) Vassals and Robbers (vassals-and-robbers)"
echo "  3) Artel"
echo ""
read -p "Выбор [1-3]: " GAME_CHOICE

case "$GAME_CHOICE" in
    1)
        GAME_NAME="Era of Change"
        ACTIVE_GAME="base-game"
        ANDROID_FLAVOR_CAP="Base"
        IOS_SCHEME="era_native"
        ;;
    2)
        GAME_NAME="Vassals and Robbers"
        ACTIVE_GAME="vassals-and-robbers"
        ANDROID_FLAVOR_CAP="Vassals"
        IOS_SCHEME="Vassals"
        ;;
    3)
        GAME_NAME="Artel"
        ACTIVE_GAME="artel"
        ANDROID_FLAVOR_CAP="Artel"
        IOS_SCHEME="Artel"
        ;;
    *)
        echo -e "${YELLOW}Неверный выбор. Используется base-game.${NC}"
        GAME_NAME="Era of Change"
        ACTIVE_GAME="base-game"
        ANDROID_FLAVOR_CAP="Base"
        IOS_SCHEME="era_native"
        ;;
esac

echo ""
echo -e "${GREEN}Выбрана игра: ${GAME_NAME}${NC}"
echo -e "${GREEN}ACTIVE_GAME: ${ACTIVE_GAME}${NC}\n"

# Update config.ts with production settings and selected game
echo -e "${YELLOW}Updating ${PROJECT_APP} configuration for production...${NC}"
cat > ${PROJECT_APP}/src/config.ts <<EOF
// This file is auto-generated by era_scripts/build-prod.sh on $(date)
// Production configuration with Basic Auth
export const CONFIG = {
  ACTIVE_GAME: '${ACTIVE_GAME}',
  BACKEND_URL: '${PROD_BACKEND_URL}',
  BASIC_AUTH: {
    username: '${PROD_BASIC_AUTH_USERNAME}',
    password: '${PROD_BASIC_AUTH_PASSWORD}',
  },
};
EOF

echo -e "${GREEN}✓ Configuration updated${NC}\n"

# Ask user what to build
echo -e "${YELLOW}Что хотите собрать?${NC}"
echo "  1) Android APK/AAB"
echo "  2) iOS (требуется Mac)"
echo "  3) Только обновить конфигурацию (без сборки)"
echo ""
read -p "Выбор [1-3]: " BUILD_CHOICE

case "$BUILD_CHOICE" in
    1)
        echo ""
        echo -e "${YELLOW}=== Android Build ===${NC}"
        echo -e "${BLUE}Выберите тип сборки:${NC}"
        echo "  1) APK (debug/release)"
        echo "  2) AAB (release для Google Play)"
        echo ""
        read -p "Выбор [1-2]: " ANDROID_TYPE
        
        cd "$PROJECT_DIR/${PROJECT_APP}"

        if [ "$ANDROID_TYPE" = "1" ]; then
            echo ""
            echo -e "${YELLOW}Создание APK...${NC}"
            echo -e "${BLUE}Выберите вариант:${NC}"
            echo "  1) Debug APK"
            echo "  2) Release APK"
            echo ""
            read -p "Выбор [1-2]: " APK_TYPE

            if [ "$APK_TYPE" = "1" ]; then
                echo -e "${GREEN}Сборка Debug APK...${NC}"
                cd android
                ./gradlew "assemble${ANDROID_FLAVOR_CAP}Debug"
                echo ""
                echo -e "${GREEN}✓ Debug APK создан${NC}"
                echo -e "${BLUE}Flavor: ${ACTIVE_GAME}${NC}"
                echo -e "${BLUE}Путь: ${PROJECT_APP}/android/app/build/outputs/apk/${ANDROID_FLAVOR_CAP,,}/debug/${NC}"
            else
                echo -e "${GREEN}Сборка Release APK...${NC}"
                echo -e "${YELLOW}Примечание: требуется настроенный keystore${NC}"
                cd android
                ./gradlew "assemble${ANDROID_FLAVOR_CAP}Release"
                echo ""
                echo -e "${GREEN}✓ Release APK создан${NC}"
                echo -e "${BLUE}Flavor: ${ACTIVE_GAME}${NC}"
                echo -e "${BLUE}Путь: ${PROJECT_APP}/android/app/build/outputs/apk/${ANDROID_FLAVOR_CAP,,}/release/${NC}"
            fi
        else
            echo ""
            echo -e "${GREEN}Сборка AAB для Google Play...${NC}"
            echo -e "${YELLOW}Примечание: требуется настроенный keystore${NC}"
            cd android
            ./gradlew "bundle${ANDROID_FLAVOR_CAP}Release"
            echo ""
            echo -e "${GREEN}✓ AAB создан${NC}"
            echo -e "${BLUE}Flavor: ${ACTIVE_GAME}${NC}"
            echo -e "${BLUE}Путь: ${PROJECT_APP}/android/app/build/outputs/bundle/${ANDROID_FLAVOR_CAP,,}Release/${NC}"
        fi

        cd "$PROJECT_DIR"
        ;;
    2)
        echo ""
        echo -e "${YELLOW}=== iOS Build ===${NC}"
        echo -e "${RED}Внимание: iOS сборка требует Mac и настроенный Xcode${NC}"

        cd "$PROJECT_DIR/${PROJECT_APP}/ios"
        
        echo -e "${GREEN}Установка Pods...${NC}"
        pod install
        
        echo ""
        echo -e "${YELLOW}Откройте ${PROJECT_APP}/ios/${PROJECT_APP}.xcworkspace в Xcode для сборки${NC}"
        echo -e "${BLUE}Выбранная схема: ${IOS_SCHEME}${NC}"
        echo -e "${BLUE}Или выполните: xcodebuild -workspace ${PROJECT_APP}.xcworkspace -scheme ${IOS_SCHEME} -configuration Release${NC}"
        
        cd "$PROJECT_DIR"
        ;;
    3)
        echo ""
        echo -e "${GREEN}✓ Конфигурация обновлена для продакшн${NC}"
        echo -e "${YELLOW}Вы можете собрать приложение позже используя стандартные команды React Native${NC}"
        ;;
    *)
        echo -e "${YELLOW}Неверный выбор. Только обновлена конфигурация.${NC}"
        ;;
esac

echo ""
echo -e "${GREEN}=== Готово ===${NC}"
echo -e "${BLUE}Примечание: для возврата к dev-режиму запустите ./era_scripts/start-dev.sh${NC}"
echo ""








