#!/bin/bash
# Development startup script for ERA project
# Launches backend (Rails), frontend (Vite), and mobile (Expo) in tmux sessions

set -e

# Get the directory where this script is located (era_scripts/)
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the project root directory (one level up)
PROJECT_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== ERA Development Startup ===${NC}\n"

# Check if tmux is installed
if ! command -v tmux &> /dev/null; then
    echo -e "${RED}ERROR: tmux is not installed${NC}"
    echo "Please install tmux: sudo apt-get install tmux"
    exit 1
fi

# Detect IP address
echo -e "${YELLOW}Detecting system IP address...${NC}"
source "$SCRIPTS_DIR/get-ip.sh"
if [ -z "$DEV_IP" ]; then
    echo -e "${RED}Failed to detect IP address${NC}"
    exit 1
fi

# Load environment variables
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Set default ports if not already set
export BACKEND_PORT=${BACKEND_PORT:-3000}
export FRONTEND_PORT=${FRONTEND_PORT:-5173}
export BACKEND_URL="http://${DEV_IP}:${BACKEND_PORT}"
export FRONTEND_URL="http://${DEV_IP}:${FRONTEND_PORT}"

echo -e "\n${GREEN}Configuration:${NC}"
echo -e "  IP Address:   ${DEV_IP}"
echo -e "  Backend URL:  ${BACKEND_URL}"
echo -e "  Frontend URL: ${FRONTEND_URL}"
echo ""

# Update frontend .env.development file
cat > era_front/.env.development <<EOF
# Auto-generated by start-dev.sh on $(date)
VITE_PROXY=${BACKEND_URL}
EOF

# Update era_native config.ts with backend URL
echo -e "${YELLOW}Updating era_native configuration...${NC}"
cat > era_native/src/config.ts <<EOF
// This file is auto-generated by era_scripts/start-dev.sh on $(date)
// Default values are used when running without the script
export const CONFIG = {
  BACKEND_URL: '${BACKEND_URL}',
};
EOF

# Ask user about mobile app startup mode
echo -e "\n${YELLOW}Запустить мобильное приложение (era_native)?${NC}"
echo "  1) Да, запустить Metro bundler"
echo "  2) Нет, пропустить"
echo ""
read -p "Выбор [1-2]: " MOBILE_CHOICE

MOBILE_CMD=""
MOBILE_DESC="Skipped"
RUN_ANDROID=""

if [ "$MOBILE_CHOICE" = "1" ]; then
    MOBILE_CMD="npx react-native start --reset-cache"
    MOBILE_DESC="React Native (Metro)"
    
    echo ""
    echo -e "${YELLOW}Хотите также запустить сборку на Android устройство?${NC}"
    echo -e "${BLUE}(Команда: npx react-native run-android)${NC}"
    echo "  1) Да, запустить сборку на устройство"
    echo "  2) Нет, только Metro bundler"
    echo ""
    read -p "Выбор [1-2]: " ANDROID_CHOICE
    
    if [ "$ANDROID_CHOICE" = "1" ]; then
        RUN_ANDROID="yes"
    fi
fi

# If user chose to build on Android device, do it now before starting tmux
if [ "$RUN_ANDROID" = "yes" ]; then
    echo ""
    echo -e "${GREEN}=== Сборка и установка на Android устройство ===${NC}"
    echo -e "${YELLOW}Убедитесь, что устройство подключено и отладка по USB включена${NC}"
    echo -e "${BLUE}Это может занять несколько минут при первой сборке...${NC}"
    echo ""
    
    cd "$PROJECT_DIR/era_native"
    
    if npx react-native run-android; then
        echo ""
        echo -e "${GREEN}✓ Сборка успешно завершена и установлена на устройство!${NC}"
        echo -e "${BLUE}Теперь запускаем Metro bundler в tmux...${NC}"
        echo ""
        sleep 2
    else
        echo ""
        echo -e "${RED}✗ Ошибка при сборке приложения${NC}"
        echo -e "${YELLOW}Продолжаем запуск остальных сервисов...${NC}"
        echo ""
        sleep 2
    fi
    
    cd "$PROJECT_DIR"
fi

# Session name
SESSION_NAME="era-dev"

# Kill existing session if it exists
tmux has-session -t $SESSION_NAME 2>/dev/null && tmux kill-session -t $SESSION_NAME

echo -e "\n${GREEN}Starting tmux session: ${SESSION_NAME}${NC}\n"

# Create new tmux session with backend
tmux new-session -d -s $SESSION_NAME -n "ERA Development"

# Setup backend pane (top)
tmux send-keys -t $SESSION_NAME "cd '$PROJECT_DIR/eraofchange'" C-m
tmux send-keys -t $SESSION_NAME "clear" C-m
tmux send-keys -t $SESSION_NAME "echo -e '${BLUE}=== Backend (Rails) ===${NC}'" C-m
tmux send-keys -t $SESSION_NAME "echo 'Starting Rails server on ${BACKEND_URL}...'" C-m
tmux send-keys -t $SESSION_NAME "echo ''" C-m
tmux send-keys -t $SESSION_NAME "rvm use" C-m
tmux send-keys -t $SESSION_NAME "export DEV_IP='${DEV_IP}'" C-m
tmux send-keys -t $SESSION_NAME "export BACKEND_PORT='${BACKEND_PORT}'" C-m
tmux send-keys -t $SESSION_NAME "export PORT='${BACKEND_PORT}'" C-m
tmux send-keys -t $SESSION_NAME "rails s -b ${DEV_IP} -p ${BACKEND_PORT}" C-m

# Split window horizontally for frontend (bottom)
tmux split-window -v -t $SESSION_NAME
tmux send-keys -t $SESSION_NAME "cd '$PROJECT_DIR/era_front'" C-m
tmux send-keys -t $SESSION_NAME "clear" C-m
tmux send-keys -t $SESSION_NAME "echo -e '${BLUE}=== Frontend (Vite) ===${NC}'" C-m
tmux send-keys -t $SESSION_NAME "echo 'Starting Vite dev server on ${FRONTEND_URL}...'" C-m
tmux send-keys -t $SESSION_NAME "echo ''" C-m
tmux send-keys -t $SESSION_NAME "sleep 3" C-m
tmux send-keys -t $SESSION_NAME "export DEV_IP='${DEV_IP}'" C-m
tmux send-keys -t $SESSION_NAME "export FRONTEND_PORT='${FRONTEND_PORT}'" C-m
tmux send-keys -t $SESSION_NAME "pnpm dev --host ${DEV_IP} --port ${FRONTEND_PORT}" C-m

# Split the bottom pane vertically for mobile (if not skipped)
if [ -n "$MOBILE_CMD" ]; then
    tmux split-window -h -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME "cd '$PROJECT_DIR/era_native'" C-m
    tmux send-keys -t $SESSION_NAME "clear" C-m
    tmux send-keys -t $SESSION_NAME "echo -e '${BLUE}=== Mobile (React Native) ===${NC}'" C-m
    tmux send-keys -t $SESSION_NAME "echo 'Starting Metro bundler (${MOBILE_DESC})...'" C-m
    tmux send-keys -t $SESSION_NAME "echo 'Backend URL: ${BACKEND_URL}'" C-m
    
    # Show info based on whether Android build was done
    if [ "$RUN_ANDROID" = "yes" ]; then
        tmux send-keys -t $SESSION_NAME "echo -e '${GREEN}Приложение уже установлено на устройство${NC}'" C-m
    else
        tmux send-keys -t $SESSION_NAME "echo -e '${YELLOW}Напоминание: для запуска на устройство выполните:${NC}'" C-m
        tmux send-keys -t $SESSION_NAME "echo -e '${GREEN}npx react-native run-android${NC}'" C-m
    fi
    
    tmux send-keys -t $SESSION_NAME "echo ''" C-m
    tmux send-keys -t $SESSION_NAME "sleep 3" C-m
    tmux send-keys -t $SESSION_NAME "${MOBILE_CMD}" C-m
fi

# Adjust pane sizes (backend gets more space)
tmux select-layout -t $SESSION_NAME main-horizontal

# Select the backend pane
tmux select-pane -t $SESSION_NAME:0.0

echo -e "${GREEN}✓ Tmux session created successfully!${NC}\n"
echo -e "${YELLOW}Commands:${NC}"
echo -e "  Attach to session:    ${GREEN}tmux attach -t ${SESSION_NAME}${NC}"
echo -e "  Detach from session:  ${GREEN}Ctrl+B, then D${NC}"
echo -e "  Switch panes:         ${GREEN}Ctrl+B, then arrow keys${NC}"
echo -e "  Kill session:         ${GREEN}tmux kill-session -t ${SESSION_NAME}${NC}"
echo ""
echo -e "${YELLOW}Services:${NC}"
echo -e "  Backend:  ${BACKEND_URL}"
echo -e "  Frontend: ${FRONTEND_URL}"
if [ -n "$MOBILE_CMD" ]; then
    echo -e "  Mobile:   ${MOBILE_DESC}"
fi
echo ""
echo -e "${GREEN}Attaching to session...${NC}"
echo ""

# Give services a moment to start before attaching
sleep 1

# Attach to the session
tmux attach -t $SESSION_NAME

