#!/bin/bash
# Development startup script for ERA project
# Launches backend (Rails), frontend (Vite), and mobile (Expo) in tmux sessions

set -e

# Get the directory where this script is located (era_scripts/)
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the project root directory (one level up)
PROJECT_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== ERA Development Startup ===${NC}\n"

# Ask user which game to run (unless already set)
if [ -z "$GAME_CHOICE" ]; then
    echo -e "${YELLOW}Выберите игру для запуска:${NC}"
    echo "  1) base-game (Era of Change - базовая игра)"
    echo "  2) vassals-and-robbers (Vassals and Robbers - новая игра)"
    echo ""
    read -p "Выбор [1-2]: " GAME_CHOICE
fi

case "$GAME_CHOICE" in
    1)
        ACTIVE_GAME="base-game"
        VITE_ACTIVE_GAME="base-game"
        ;;
    2)
        ACTIVE_GAME="vassals-and-robbers"
        VITE_ACTIVE_GAME="vassals-and-robbers"
        ;;
    *)
        echo -e "${YELLOW}Неверный выбор. Используется base-game${NC}"
        ACTIVE_GAME="base-game"
        VITE_ACTIVE_GAME="base-game"
        ;;
esac

echo -e "\n${GREEN}Выбрана игра: ${ACTIVE_GAME}${NC}\n"

# Check if tmux is installed
if ! command -v tmux &> /dev/null; then
    echo -e "${RED}ERROR: tmux is not installed${NC}"
    echo "Please install tmux: sudo apt-get install tmux"
    exit 1
fi

# Detect IP address
echo -e "${YELLOW}Detecting system IP address...${NC}"
source "$SCRIPTS_DIR/get-ip.sh"
if [ -z "$DEV_IP" ]; then
    echo -e "${RED}Failed to detect IP address${NC}"
    exit 1
fi

# Load environment variables
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Set default ports if not already set
export BACKEND_PORT=${BACKEND_PORT:-3000}
export FRONTEND_PORT=${FRONTEND_PORT:-5173}
export BACKEND_URL="http://${DEV_IP}:${BACKEND_PORT}"
export FRONTEND_URL="http://${DEV_IP}:${FRONTEND_PORT}"

echo -e "\n${GREEN}Configuration:${NC}"
echo -e "  Active Game:  ${ACTIVE_GAME}"
echo -e "  IP Address:   ${DEV_IP}"
echo -e "  Backend URL:  ${BACKEND_URL}"
echo -e "  Frontend URL: ${FRONTEND_URL}"
echo ""

# Update frontend .env.development file
cat > era_front/.env.development <<EOF
# Auto-generated by start-dev.sh on $(date)
VITE_PROXY=${BACKEND_URL}
VITE_ACTIVE_GAME=${VITE_ACTIVE_GAME}
EOF

# Update era_native config.ts with backend URL
echo -e "${YELLOW}Updating era_native configuration...${NC}"
cat > era_native/src/config.ts <<EOF
// This file is auto-generated by era_scripts/start-dev.sh on $(date)
// Default values are used when running without the script
export const CONFIG = {
  BACKEND_URL: '${BACKEND_URL}',
};
EOF

# Update era_native .env with active game
cat > era_native/.env <<EOF
# Auto-generated by start-dev.sh on $(date)
ACTIVE_GAME=${ACTIVE_GAME}
BACKEND_URL=${BACKEND_URL}
EOF

# Function to detect Android devices
detect_android_devices() {
    echo -e "${YELLOW}Обнаружение Android устройств...${NC}"
    
    # Check if adb is available
    if ! command -v adb &> /dev/null; then
        echo -e "${RED}ADB не найден. Установите Android SDK Platform Tools${NC}"
        return 1
    fi
    
    # Get list of devices
    adb devices -l | grep -v "List of devices" | grep -v "^$" > /tmp/adb_devices.txt
    
    if [ ! -s /tmp/adb_devices.txt ]; then
        echo -e "${RED}Устройства не найдены${NC}"
        echo -e "${YELLOW}Убедитесь что:${NC}"
        echo "  - Устройство подключено по USB"
        echo "  - Отладка по USB включена на устройстве"
        echo "  - Драйверы установлены (для Windows)"
        echo ""
        return 1
    fi
    
    echo -e "${GREEN}Найденные устройства:${NC}"
    echo ""
    
    # Parse and display devices
    local i=1
    declare -g -A DEVICES
    while IFS= read -r line; do
        if [[ $line =~ ^([a-zA-Z0-9]+)[[:space:]]+device ]]; then
            device_id="${BASH_REMATCH[1]}"
            # Extract model name if available
            if [[ $line =~ model:([^[:space:]]+) ]]; then
                model="${BASH_REMATCH[1]}"
            else
                model="Unknown"
            fi
            # Extract product if available
            if [[ $line =~ product:([^[:space:]]+) ]]; then
                product="${BASH_REMATCH[1]}"
            else
                product="Unknown"
            fi
            
            DEVICES[$i]="$device_id"
            echo -e "  ${i}) ${GREEN}${device_id}${NC} - ${model} (${product})"
            ((i++))
        fi
    done < /tmp/adb_devices.txt
    
    echo ""
    return 0
}

# Ask user about mobile app startup mode (unless already set)
if [ -z "$MOBILE_CHOICE" ]; then
    echo -e "\n${YELLOW}Запустить мобильное приложение (era_native)?${NC}"
    echo "  1) Да, запустить Metro bundler"
    echo "  2) Нет, пропустить"
    echo ""
    read -p "Выбор [1-2]: " MOBILE_CHOICE
fi

MOBILE_CMD=""
MOBILE_DESC="Skipped"
RUN_ANDROID=""
SELECTED_DEVICE=""

if [ "$MOBILE_CHOICE" = "1" ]; then
    MOBILE_CMD="npx react-native start --reset-cache"
    MOBILE_DESC="React Native (Metro)"
    
    echo ""
    echo -e "${YELLOW}Хотите также запустить сборку на Android устройство?${NC}"
    echo -e "${BLUE}(Команда: npx react-native run-android)${NC}"
    echo "  1) Да, запустить сборку на устройство"
    echo "  2) Нет, только Metro bundler"
    echo ""
    read -p "Выбор [1-2]: " ANDROID_CHOICE
    
    if [ "$ANDROID_CHOICE" = "1" ]; then
        RUN_ANDROID="yes"
        
        # Detect and select Android device
        echo ""
        if detect_android_devices; then
            device_count=${#DEVICES[@]}
            
            if [ $device_count -eq 1 ]; then
                SELECTED_DEVICE="${DEVICES[1]}"
                echo -e "${GREEN}Автоматически выбрано единственное устройство: ${SELECTED_DEVICE}${NC}"
            else
                echo -e "${YELLOW}Выберите устройство для установки:${NC}"
                read -p "Номер устройства [1-${device_count}]: " DEVICE_CHOICE
                
                if [ -n "${DEVICES[$DEVICE_CHOICE]}" ]; then
                    SELECTED_DEVICE="${DEVICES[$DEVICE_CHOICE]}"
                    echo -e "${GREEN}Выбрано устройство: ${SELECTED_DEVICE}${NC}"
                else
                    echo -e "${RED}Неверный выбор. Будет использовано устройство по умолчанию${NC}"
                fi
            fi
        else
            echo -e "${YELLOW}Продолжаем без выбора конкретного устройства${NC}"
        fi
    fi
fi

# If user chose to build on Android device, do it now before starting tmux
if [ "$RUN_ANDROID" = "yes" ]; then
    echo ""
    echo -e "${GREEN}=== Сборка и установка на Android устройство ===${NC}"
    
    if [ -n "$SELECTED_DEVICE" ]; then
        echo -e "${YELLOW}Устройство: ${GREEN}${SELECTED_DEVICE}${NC}"
    else
        echo -e "${YELLOW}Убедитесь, что устройство подключено и отладка по USB включена${NC}"
    fi
    
    echo -e "${BLUE}Это может занять несколько минут при первой сборке...${NC}"
    echo ""
    
    cd "$PROJECT_DIR/era_native"
    
    # Build command with optional device ID
    if [ -n "$SELECTED_DEVICE" ]; then
        BUILD_CMD="npx react-native run-android --deviceId=${SELECTED_DEVICE}"
    else
        BUILD_CMD="npx react-native run-android"
    fi
    
    echo -e "${BLUE}Выполняется: ${BUILD_CMD}${NC}"
    echo ""
    
    if $BUILD_CMD; then
        echo ""
        echo -e "${GREEN}✓ Сборка успешно завершена и установлена на устройство!${NC}"
        if [ -n "$SELECTED_DEVICE" ]; then
            echo -e "${GREEN}✓ Устройство: ${SELECTED_DEVICE}${NC}"
        fi
        echo -e "${BLUE}Теперь запускаем Metro bundler в tmux...${NC}"
        echo ""
        sleep 2
    else
        echo ""
        echo -e "${RED}✗ Ошибка при сборке приложения${NC}"
        echo -e "${YELLOW}Продолжаем запуск остальных сервисов...${NC}"
        echo ""
        sleep 2
    fi
    
    cd "$PROJECT_DIR"
fi

# Session name
SESSION_NAME="era-dev"

# Kill existing session if it exists
tmux has-session -t $SESSION_NAME 2>/dev/null && tmux kill-session -t $SESSION_NAME

echo -e "\n${GREEN}Starting tmux session: ${SESSION_NAME}${NC}\n"

# Create new tmux session with backend
tmux new-session -d -s $SESSION_NAME -n "ERA Development"

# Setup backend pane (top)
tmux send-keys -t $SESSION_NAME "cd '$PROJECT_DIR/eraofchange'" C-m
tmux send-keys -t $SESSION_NAME "clear" C-m
tmux send-keys -t $SESSION_NAME "echo -e '${BLUE}=== Backend (Rails) ===${NC}'" C-m
tmux send-keys -t $SESSION_NAME "echo 'Starting Rails server on ${BACKEND_URL}...'" C-m
tmux send-keys -t $SESSION_NAME "echo ''" C-m
tmux send-keys -t $SESSION_NAME "rvm use" C-m
tmux send-keys -t $SESSION_NAME "export DEV_IP='${DEV_IP}'" C-m
tmux send-keys -t $SESSION_NAME "export BACKEND_PORT='${BACKEND_PORT}'" C-m
tmux send-keys -t $SESSION_NAME "export PORT='${BACKEND_PORT}'" C-m
tmux send-keys -t $SESSION_NAME "export ACTIVE_GAME='${ACTIVE_GAME}'" C-m
tmux send-keys -t $SESSION_NAME "rails s -b ${DEV_IP} -p ${BACKEND_PORT}" C-m

# Split window horizontally for frontend (bottom)
tmux split-window -v -t $SESSION_NAME
tmux send-keys -t $SESSION_NAME "cd '$PROJECT_DIR/era_front'" C-m
tmux send-keys -t $SESSION_NAME "clear" C-m
tmux send-keys -t $SESSION_NAME "echo -e '${BLUE}=== Frontend (Vite) ===${NC}'" C-m
tmux send-keys -t $SESSION_NAME "echo 'Starting Vite dev server on ${FRONTEND_URL}...'" C-m
tmux send-keys -t $SESSION_NAME "echo ''" C-m
tmux send-keys -t $SESSION_NAME "sleep 3" C-m
tmux send-keys -t $SESSION_NAME "export DEV_IP='${DEV_IP}'" C-m
tmux send-keys -t $SESSION_NAME "export FRONTEND_PORT='${FRONTEND_PORT}'" C-m
tmux send-keys -t $SESSION_NAME "export VITE_ACTIVE_GAME='${VITE_ACTIVE_GAME}'" C-m
tmux send-keys -t $SESSION_NAME "pnpm dev --host ${DEV_IP} --port ${FRONTEND_PORT}" C-m

# Split the bottom pane vertically for mobile (if not skipped)
if [ -n "$MOBILE_CMD" ]; then
    tmux split-window -h -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME "cd '$PROJECT_DIR/era_native'" C-m
    tmux send-keys -t $SESSION_NAME "clear" C-m
    tmux send-keys -t $SESSION_NAME "echo -e '${BLUE}=== Mobile (React Native) ===${NC}'" C-m
    tmux send-keys -t $SESSION_NAME "echo 'Starting Metro bundler (${MOBILE_DESC})...'" C-m
    tmux send-keys -t $SESSION_NAME "echo 'Backend URL: ${BACKEND_URL}'" C-m
    
    # Show info based on whether Android build was done
    if [ "$RUN_ANDROID" = "yes" ]; then
        if [ -n "$SELECTED_DEVICE" ]; then
            tmux send-keys -t $SESSION_NAME "echo -e '${GREEN}Приложение установлено на: ${SELECTED_DEVICE}${NC}'" C-m
        else
            tmux send-keys -t $SESSION_NAME "echo -e '${GREEN}Приложение уже установлено на устройство${NC}'" C-m
        fi
    else
        tmux send-keys -t $SESSION_NAME "echo -e '${YELLOW}Напоминание: для запуска на устройство выполните:${NC}'" C-m
        tmux send-keys -t $SESSION_NAME "echo -e '${GREEN}npx react-native run-android${NC}'" C-m
    fi
    
    tmux send-keys -t $SESSION_NAME "echo ''" C-m
    tmux send-keys -t $SESSION_NAME "sleep 3" C-m
    tmux send-keys -t $SESSION_NAME "${MOBILE_CMD}" C-m
fi

# Adjust pane sizes (backend gets more space)
tmux select-layout -t $SESSION_NAME main-horizontal

# Select the backend pane
tmux select-pane -t $SESSION_NAME:0.0

echo -e "${GREEN}✓ Tmux session created successfully!${NC}\n"
echo -e "${YELLOW}Commands:${NC}"
echo -e "  Attach to session:    ${GREEN}tmux attach -t ${SESSION_NAME}${NC}"
echo -e "  Detach from session:  ${GREEN}Ctrl+B, then D${NC}"
echo -e "  Switch panes:         ${GREEN}Ctrl+B, then arrow keys${NC}"
echo -e "  Kill session:         ${GREEN}tmux kill-session -t ${SESSION_NAME}${NC}"
echo ""
echo -e "${YELLOW}Services:${NC}"
echo -e "  Active Game: ${GREEN}${ACTIVE_GAME}${NC}"
echo -e "  Backend:     ${BACKEND_URL}"
echo -e "  Frontend:    ${FRONTEND_URL}"
if [ -n "$MOBILE_CMD" ]; then
    echo -e "  Mobile:      ${MOBILE_DESC}"
fi
echo ""
echo -e "${GREEN}Attaching to session...${NC}"
echo ""

# Give services a moment to start before attaching
sleep 1

# Attach to the session
tmux attach -t $SESSION_NAME

